services:
  - type: web
    name: bibliotheque-proj
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bibliotheque_project.wsgi:application
    runtime: python-3.11.9